export {
  managePagePermissions,
  getManagementPageAccessState,
  getDefaultManagementRoute,
  getPageDefinition,
  getVisibleManagementSections,
  hasPagePermission,
  managementPageSections,
  type ManagementAccessMetadata,
  type ManagementPageDefinition,
  type ManagementSectionKey,
  type PageAccess,
  type PageAccessSection,
  type PagePermission,
} from "@/lib/management-access"
